
[destination.postgres.credentials]
database = "ny_taxi" # please set me up!
password = "root" # please set me up!
username = "root" # please set me up!
host = "localhost" # please set me up!
port = 5431
connect_timeout = 15
